jobs:
  release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - env:
          PYPI_UPLOAD: true
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        name: Build and release
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
name: Upload Python Package
on: workflow_call
permissions:
  contents: read
